import type { Metadata } from 'next';
import { Noto_Sans_TC as notoSansTC } from 'next/font/google';

import Providers from '@/providers/Providers';
import '@/styles/globals.css';

const notoSans = notoSansTC({
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'orangeLife App',
  description: 'Generated by orangeLife app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Providers>
          <main className="relative h-dvh">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
