import type { Metadata } from 'next';
import { Noto_Sans_TC as notoSansTC } from 'next/font/google';

import Header from '@/components/Header';
import SideNavigation from '@/components/SideNavigation';
import '@/styles/globals.css';

const notoSans = notoSansTC({
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'orangeLife App',
  description: 'Generated by orangeLife app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} relative flex min-h-screen flex-col bg-primary-0 text-primary-700`}
      >
        <Header />
        <main className="flex flex-1">
          <SideNavigation />
          <main className="mx-auto w-full max-w-screen-md px-4 pt-10">
            {children}
          </main>
        </main>
      </body>
    </html>
  );
}
